### PR TITLE
Added and wrote code for todos from tutorial

### PR DESCRIPTION
**Pull request by AbuTalha3**
**In this PR I have:-**
- Tried to learn making a TODO APP with the help of a react tutorial.
image

### CODE REVIEW

**Review by nejidevelops — APPROVED** [review]
# :heavy_check_mark:Code Review Approval - Exceptional Work!

Dear @AbuTalha3 ,

I hope this message finds you well. I've just completed a thorough review of your code, and I must say, I am thoroughly impressed! Your code not only meets but exceeds our expectations. It's clear that you've put in a lot of thought, effort, and skill into this project, and I couldn't be happier with the results.

- Here are some of the highlights that stood out during my review:

1. **Clarity and Readability**: Your code is exceptionally well-structured and easy to follow. The use of meaningful variable names, comments, and a consistent coding style makes it a pleasure to review.

2. **Efficiency**: Your code runs smoothly without any noticeable performance bottlenecks. You've demonstrated a deep understanding of the problem domain and optimized the code accordingly.

3. **Error Handling**: I particularly appreciate the robust error handling you've implemented. It gracefully handles unexpected situations, ensuring a more resilient and user-friendly application.

4. **Test Coverage**: Your comprehensive test suite provides excellent coverage, leaving no room for ambiguity. It's evident that you've considered various scenarios and edge cases.

5. **Documentation**: The inline comments and documentation you've included are informative and help other developers understand the code's functionality quickly.

6. **Consistency**: Your code aligns perfectly with our coding standards and best practices. This consistency is crucial for maintainability and collaboration.

7. **Security**: I'm pleased to see that you've taken security seriously by implementing security measures such as input validation and secure data handling.

8. **Scalability**: Your code is scalable, which is vital for the long-term success of our project. It's designed in a way that makes future enhancements and modifications straightforward.

Here's a little celebration gif to express my excitement about your work:

Approval Gif

Your dedication and commitment to delivering high-quality code have not gone unnoticed. Your contributions are truly valuable to the team and the project as a whole. I have no hesitation in approving this code for deployment.

Once again, excellent job, @AbuTalha3 ! Thank you for your hard work and dedication. Let's continue to raise the bar for excellence in our development efforts.

If you have any questions or need further support, please don't hesitate to reach out. Keep up the fantastic work!

Best regards,
Mohammad Newton Hassan

**Comment by nejidevelops** [comment]
@AbuTalha3 time to now make some beautiful styling of the webpage to make it look top notch :dart:

**Comment by AbuTalha3** [comment]
thank u for being there

**Review by HenaryKhuraijam — COMMENTED** [review]
Hi @AbuTalha3 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- [ ] All requested changes are made ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
